# Generated by Django 3.0 on 2020-10-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20201005_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('BS', 'Best Seller')], max_length=2),
        ),
    ]
